//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfAccount
    {
        public int ID { get; set; }
        public int CustomerRef { get; set; }
        public int TypeRef { get; set; }
        public double Amount { get; set; }
        public string Discription { get; set; }
        public System.DateTime DateTitle { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual AccountingTypes AccountingTypes { get; set; }
        public virtual Customer Customers { get; set; }
    }
}
